"""
bundle_web_data.py
Exports the clean dataset, EDA metrics, and data dictionary as JavaScript variables
so the website works natively both under HTTP/HTTPS and direct file:/// browser opening.
"""

import json
import os

def bundle_data():
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    clean_json_path = os.path.join(base_dir, 'data', 'cleaned', 'college_food_choices_clean.json')
    eda_json_path = os.path.join(base_dir, 'analysis', 'EDA', 'eda_summary.json')
    dict_json_path = os.path.join(base_dir, 'documentation', 'data_dictionary.json')
    
    js_output_dir = os.path.join(base_dir, 'website', 'assets', 'js')
    os.makedirs(js_output_dir, exist_ok=True)

    with open(clean_json_path, 'r', encoding='utf-8') as f:
        clean_data = json.load(f)

    with open(eda_json_path, 'r', encoding='utf-8') as f:
        eda_data = json.load(f)

    with open(dict_json_path, 'r', encoding='utf-8') as f:
        dict_data = json.load(f)

    # 1. Dataset JS
    dataset_js_file = os.path.join(js_output_dir, 'dataset.js')
    with open(dataset_js_file, 'w', encoding='utf-8') as f:
        f.write("// Autogenerated from data/cleaned/college_food_choices_clean.json\n")
        f.write("window.COLLEGE_FOOD_DATA = ")
        json.dump(clean_data, f)
        f.write(";\n")
    print("Bundled dataset.js with {} records".format(len(clean_data)))

    # 2. EDA JS
    eda_js_file = os.path.join(js_output_dir, 'eda_data.js')
    with open(eda_js_file, 'w', encoding='utf-8') as f:
        f.write("// Autogenerated from analysis/EDA/eda_summary.json\n")
        f.write("window.EDA_SUMMARY = ")
        json.dump(eda_data, f, indent=2)
        f.write(";\n")
    print("Bundled eda_data.js")

    # 3. Data Dictionary JS
    dict_js_file = os.path.join(js_output_dir, 'dictionary_data.js')
    with open(dict_js_file, 'w', encoding='utf-8') as f:
        f.write("// Autogenerated from documentation/data_dictionary.json\n")
        f.write("window.DATA_DICTIONARY = ")
        json.dump(dict_data, f, indent=2)
        f.write(";\n")
    print("Bundled dictionary_data.js with {} fields".format(len(dict_data)))

if __name__ == '__main__':
    bundle_data()
